name: Pipeline CI/CD for Back-End

env:
  NODE_VERSION: 12
  
on:
  push:
    paths:    
      - 'backend/**'
      - '.github/workflows/backend-pipeline.yml'
  pull_request:
    paths:    
      - 'backend/**'  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
         path: backend
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      #1 Run tests
      - name: run tests
        run: npm test
      
      #2 Run ESLint
      - name: run eslint
        uses: icrawl/action-eslint@v1
     
  deploy:
    if: github.event_name != 'pull_request'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
