name: Pipeline CI/CD for Back-End

env:
  NODE_VERSION: 12
  WORKING_DIRECTORY: ./backend
  
on:
  push:
    paths:    
      - 'backend/**'
      - '.github/workflows/backend-pipeline.yml'
  pull_request:
    paths:    
      - 'backend/**'  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      # Install dependencies
      - name: npm install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install
          
      # Run tests
      - name: run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm test
      
      # Run ESLint
      - name: run eslint
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npx eslint app/*
          


  deploy:
    if: github.event_name != 'pull_request'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
