name: Pipeline CI/CD for Back-End

env:
  NODE_VERSION: 12
  WORKING_DIRECTORY: ./backend
  TAG: ${{ github.sha }}
  
on:
  push:
    paths:    
      - 'backend/**'
      - '.github/workflows/backend-pipeline.yml'
  pull_request:
    paths:    
      - 'backend/**'  

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      # Install dependencies
      - name: npm install
        run: npm install
          
      # Run tests
      - name: run tests
        run: npm test
      
      # Run ESLint
      - name: run eslint
        run: npx eslint app/*
                   
  build:
    if: github.event_name != 'pull_request'
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build & Push to container registry
        run: |
          #docker build . -t mindzoom/users-app:${{ env.TAG }}
          #docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} 
          #docker push mindzoom/users-app:${{ env.TAG }} 
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy'
         
