name: Terraform Destroy

env:
  WORKING_DIRECTORY: ./terraform
  
on:
  push:
    paths:    
      - 'terraform/**'
      - '.github/workflows/terraform-pipeline.yml'
  pull_request:
    paths:    
      - 'terraform/**'  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
